# Project language
language: php

# Allows use container-based infrastructure
sudo: false

# Start mysql service
services:
  - mysql

# Cache composer packages so "composer install" is faster
cache:
  directories:
    - $HOME/.composer/cache/files

# Matrix to test in every php version
matrix:
  # Fast finish allows to set the build as "finished" even if the "allow_failures" matrix elements are not finished yet.
  fast_finish: true
  include:
    - php: 7.0

# Define an environment variable
env:
  - SYMFONY_VERSION="3.3.*" DB=mysql

# Update composer
before-install:
  - phpenv config-rm xdebug.ini
  - php -S localhost:8000 web
  - sleep 3

# Install composer dependencies,
# Create database, schema and fixtures
install:
  - composer self-update
  - composer install
  # Remove application cache and logs ...
  - rm -Rf var/cache/*
  - rm -Rf var/logs/*
  # Prepare application cache ...
  - php bin/console cache:warm --env=test
  # Grant application cache and logs permissions ...
  - chmod -Rf 777 var/cache/
  - chmod -Rf 777 var/logs/
  - cp app/config/parameters.yml.dist app/config/parameters.yml
  - php bin/console doctrine:database:create --env=test
  - php bin/console doctrine:schema:create --env=test
  - mkdir -p var/jwt
  - openssl genrsa -passout pass:jwt -out var/jwt/private.pem -aes256 4096
  - openssl rsa -passin pass:jwt -pubout -in var/jwt/private.pem -out var/jwt/public.pem

# After a build, send email notification with the build results
notifications:
    email: false

script: ./vendor/bin/phpunit --configuration phpunit.xml.dist