# Project language
language: php

# Allows use container-based infrastructure
sudo: false

# Start mysql service
services:
  - mysql

# Cache composer packages so "composer install" is faster
cache:
  directories:
    - $HOME/.composer/cache/files

# Matrix to test in every php version
matrix:
  # Fast finish allows to set the build as "finished" even if the "allow_failures" matrix elements are not finished yet.
  fast_finish: true
  include:
    - php: 7.0

# Define an environment variable
env:
  - SYMFONY_VERSION="3.3.*" DB=mysql
  - SOURCE_DIR=src
  - VHOST_FILE=.travis.vhost
  - VHOST_CONF=travis.conf
  - VHOST_URL=baseapi.app

# Update composer
before-install:
  - sudo cp -f $VHOST_FILE /etc/apache2/sites-available/$VHOST_CONF
  - sudo sed -e "s?%TRAVIS_BUILD_DIR%?$(pwd)?g" --in-place /etc/apache2/sites-available/$VHOST_CONF
  - sudo sed -e "s?%VHOST_URL%?$VHOST_URL?g" --in-place /etc/apache2/sites-available/$VHOST_CONF
  - echo "127.0.0.1       $VHOST_URL" | sudo tee -a /etc/hosts
  - sudo a2enmod rewrite
  - sudo a2ensite $VHOST_CONF
  - sudo service apache2 restart
  - composer self-update

# Install composer dependencies,
# Create database, schema and fixtures
install:
  - composer install --dev
  - cp app/config/parameters.yml.dist app/config/parameters.yml
  - php bin/console doctrine:database:create --env=test
  - php bin/console doctrine:schema:create --env=test
  - mkdir -p var/jwt
  - openssl genrsa -passout pass:jwt -out var/jwt/private.pem -aes256 4096
  - openssl rsa -passin pass:jwt -pubout -in var/jwt/private.pem -out var/jwt/public.pem

# After a build, send email notification with the build results
notifications:
    email: false

script: ./vendor/bin/phpunit --configuration phpunit.xml.dist