NelmioApiDocBundle:
    resource: "@NelmioApiDocBundle/Resources/config/routing.yml"
    prefix:   /api/doc

api:
    resource: '@ApiBundle/Controller/'
    type: annotation
    defaults:
        _format: json

web:
    resource: '@WebBundle/Controller/'
    type: annotation
